version: "3.9"

services:
  moderation-checker:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true